version: '3'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ../study-guide:/app/content/study-guide
      - ../labs:/app/content/labs
    environment:
      - AWS_PROFILE=default
      - BEDROCK_REGION=us-east-1
