version: '3'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ../study-guide:/app/content/study-guide
      - ../labs:/app/content/labs
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials as read-only
    environment:
      - AWS_PROFILE=default
      - BEDROCK_REGION=us-west-2  # Region where Claude models are available
